# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(choices=[('Installation', 'INSTALL'), ('Mise a jour', 'MAJ')], max_length=20, verbose_name='FAI Action'),
        ),
    ]
