# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfai', '0002_auto_20160711_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='addr',
            field=models.CharField(help_text='NAdresse MAC', max_length=17, verbose_name='Adresse MAC'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(help_text='Nom de la machine', max_length=30, verbose_name='Nom'),
        ),
    ]
