# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfai', '0003_auto_20160713_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='addr',
            field=models.CharField(help_text='Adresse MAC', max_length=17, verbose_name='Adresse MAC'),
        ),
    ]
